spring.application.name: "test"

equipment:
  speeds:
    manualWheelchair: 1.5
    electricWheelchair: 2.0
    golfCart: 5.0
    ambulift: 10.0


spring:
  datasource:
    url: jdbc:mysql://localhost:25535/testdb
    username: testuser
    password: testpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

